server:
  port: 8080

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  profiles:
    active: test
  application:
    name: review-lea
  sleuth:
    sampler:
      probability: 1.0
    log:
      slf4j:
        whitelisted-mdc-keys: principal
        enabled: true
      baggage-keys: principal
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.xml
    drop-first: false
    default-schema: review_lea
    database-change-log-table: MS_REVIEW_LEA_DBCHANGELOG
    database-change-log-lock-table: MS_REVIEW_LEA_DBCHANGELOGLOCK

